version: "3"
volumes:
  postgresql_data:
    driver: local
  bundle:
    driver: local
services:
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  webpack:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    user: ruby
    command: ["bin/yarn", "start"]
    environment:
      BUNDLE_PATH: 'vendor/bundle'
    volumes:
      - .:/src
    ports:
      - 35729:35729
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    user: ruby
    command: ["bin/rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      BUNDLE_PATH: 'vendor/bundle'
    volumes:
      - .:/src
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - db
      - webpack
