default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'db' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>

development:
  <<: *default
  database: rails_cloud_scraper_development

test:
  <<: *default
  database: rails_cloud_scraper_test

production:
  <<: *default
  database: rails_cloud_scraper_production
  username: rails_cloud_scraper
  password: <%= ENV['RAILS_CLOUD_SCRAPER_DATABASE_PASSWORD'] %>
